### ISSUE TITLE
Pairing both controllers

### ISSUE THREAD

**Issue by 20alien20** [HipsterSloth/PSMoveSteamVRBridge#103]
Hi, i have a problem with pairing both controllers. When 1st controller is paired and im trying to pair the 2nd controller the 1st always goes off. Then i can pair the 2nd controller, but simultaneously i cant use them. If my 1st controller is ON and im trying to start 2nd controller the 1st one always goes OFF. My Bluetooth adapter is only 2.0, maybe this could be the problem? I have to buy 4.0? Thanks for your time and for your answer.

**Comment by dataoverdose** [comment]
I´ve made it to connect my controllers with my Win10 Installation. After several attempts I almost gave up but this one worked:
I´ve deleted the move controllers from the Bluetooth list. Then I started the config tool, plugged the controller and selected "pair", then unplugged the USB cable and pressed the PS Button several times. Maybe the trick is to get the controller connected before windows connects it. 
Maybe this is helpful for others, too. I didn´t change any bluetooth drivers.

**Comment by 20alien20** [comment]
The problem was i had a noname 2.0 Bluetooth adapter. I bought the asus bt400, with that adapter i made the connection easily. Now i can play only beat saber, other games on steam cant recognize the 2 ps move controllers. I tried it in many ways, but nothing works.
