### ISSUE TITLE
can I use two motion controls and one navigation?

### ISSUE THREAD

**Issue by B1LLZ** [HipsterSloth/PSMoveSteamVRBridge#110]
I wanted to know if you have to use two movement controls and one navigation just to be able to move around in games and if you want to know if there is also how to connect the navigation device on the same bluetooth as the movement ones, I heard about bthPS3 which is a driver  bluetooth for PS3 accessories but I didn’t know how to configure it if someone can help me I appreciate it

**Comment by Safirnoc** [comment]
Go on youtube, you have some great tuto to setup your PSmove controller and your Cam with this plugin here.
