### ISSUE TITLE
No alignment popup when entering steamVR

### ISSUE THREAD

**Issue by shaneharris** [HipsterSloth/PSMoveSteamVRBridge#12]
The following pop up never comes up, so whilst i have a perfect calibration and everything seems to work, i never get the opportunity to sync the HMD space with the PSMoveService space. Is there a way to trigger that calibration sync manually? A hot key perhaps?

![need_alignment_gesture](https://cloud.githubusercontent.com/assets/6830845/25863728/d2b40a80-34e4-11e7-9006-b43b6ab75a02.png)

[PSMoveService.txt](https://github.com/HipsterSloth/PSMoveSteamVRBridge/files/987461/PSMoveService.txt)

**Comment by zelmon64** [comment]
Have you tried using v1.1.0? The popup should work with that version. From your log it looked like you were using  v1.0.0

**Comment by shaneharris** [comment]
you absolute legend. that sorted it
