### ISSUE TITLE
Waiting for server response... after calibrating controller tracking colors.

### ISSUE THREAD

**Issue by GoDzViper** [HipsterSloth/PSMoveSteamVRBridge#13]
As the title says every time I try to go back to the tracking settings after calibrating the tracking colors the config tool says "Waiting for server response..." and after about 10 seconds the light on the PS Move controller turns off. I then have to close the config tool and the PSMoveService to be able to use the config tool again. I am using the PSMoveSteamVRBridge Version 1.1.0

PSMoveService.Log File: https://pastebin.com/kG4By0fR

**Comment by zelmon64** [comment]
I'm pretty sure that's a USB bandwidth bottleneck slowing things down. Have you checked whether you're receiving the set frame rate and have you tried lowering it?

In the future please post these sort of problems on the google group and only post an issue here once an issue with / modification to the code has been identified. I'm closing this but we can continue discussing it here or on the gg.
