### ISSUE TITLE
Dividing controls among hands

### ISSUE THREAD

**Issue by TheSmg** [HipsterSloth/PSMoveSteamVRBridge#14]
Is it currently possible to have separate control profiles for each ps move controller? I couldn't find any documentation on this subject if this feature exists at all. This would be useful for games which require the use of both the touchpad and buttons as each set could be bound to its own controller instead of having to choose or do awkward key combinations.

**Comment by HipsterSloth** [comment]
There is currently no way to do this, though it is a feature that has been requested for a while. I've wanted to do this as an in-SteamVR UI that you could use to configure buttons. I just haven't had the time to dedicate to this.

**Comment by zelmon64** [comment]
@HipsterSloth can't this do it: https://github.com/cboulay/PSMoveService/commit/ecc68528ceb10826bf9c8a4e123b9435c934cbca? Sorry if I'm missing something obvious.

@TheSmg it's documented at the end of this subsection: https://github.com/cboulay/PSMoveService/wiki/Steam-VR-Setup#virtual-touchpad. Here's an example:

```
   "psmove_touchpad_directions_0" : {
      "circle" : "touchpad_right",
      "cross" : "touchpad_left",
      "triangle" : "touchpad_up",
      "square" : "touchpad_down"
   }, 
   "psmove_touchpad_directions_1" : {
      "circle" : "touchpad_down-right",
      "cross" : "touchpad_down-left",
      "square" : "touchpad_up-left",
      "triangle" : "touchpad_up-right"
   },
```

**Comment by TheSmg** [comment]
Thank you, dont know how I missed that. Ill try it when I get the chance

**Comment by HipsterSloth** [comment]
@zelmon64 Oh! You are absolutely right. I totally forgot you added that functionality.

**Comment by HipsterSloth** [comment]
As part of the latest release and adding support for the SteamVR Input API, each controller now has it's own config file in `%appdata%/PSMoveSteamVRBridge`

https://github.com/HipsterSloth/PSMoveSteamVRBridge/releases/tag/v1.6.0
