### ISSUE TITLE
local build - not found "PSMoveClient_CAPI.h"

### ISSUE THREAD

**Issue by gb2111** [HipsterSloth/PSMoveSteamVRBridge#20]
Hi,
I tried local build (2 times) and as result I got error that PSMoveClient_CAPI.h is not found :(

Greg

**Comment by HipsterSloth** [comment]
Did you run  scripts\msvc\InitialSetupOfficialPSM_X64.bat first?
After you open the generated .sln file you need to build the PSMoveService sub project first. This will download the PSMS release (including the file you are missing). Then you can build the entire solution.

**Comment by gb2111** [comment]
hi.
i did local build but I think there was no include file in local build. official works.
now i have issue with local build but I am 99% sure that was the case so we can close.
