### ISSUE TITLE
Wiimotes for virtual controllers / DirectInput APi rotation

### ISSUE THREAD

**Issue by ThatsEli** [HipsterSloth/PSMoveSteamVRBridge#21]
Hey, 

a guy wrote a DirectInput API for the Wiimotes([here](https://www.julianloehr.de/educational-work/hid-wiimote/)), could you get the rotation(for the virtual controllers) from that? 🤔 Would be a really nice!

**Comment by HipsterSloth** [comment]
Unfortunately that particular driver only provides the raw accelerometer values from the controller. To get an orientation you also need the gyro values from the controller (WiiMote+ only) and then you need to use a [sensor fusion algorithm](https://github.com/cboulay/PSMoveService/wiki/Sensor-Fusion) to compute an orientation from that. 

That said I think [FreePIE](https://github.com/AndersMalmgren/FreePIE) might provide this for the WiiMote. You could then write a FreePIE script to combine the orientation from the WiiMote and position from the VirtualController (using PSMoveFreePIEBridge).

**Comment by ThatsEli** [comment]
Okay, I will have a try with that, thank you!
