### ISSUE TITLE
SteamVR_InitalSetupWin64.bat File does not work.

### ISSUE THREAD

**Issue by Jeff07734** [HipsterSloth/PSMoveSteamVRBridge#26]
After setting up everything for the PSMoveService, I run the Inital Setup file and the command prompt successfully finds my SteamVR folder, but after that line it says: "'SteamVR_ReinstallDriverWin64.bat' is not recognized as a internal or external command, operable program or batch file" (The Reinstall Driver is still a batch file, as I have not changed it). This failure disallows the reinstall driver to do anything, copying zero files and constantly telling me "The system cannot find the file specified," then ending with nothing done. The SteamVR vrsettings file does have "'activateMultipleDivers' : true." I have even tried downgrading all the way to the version 1.3.0 (I didn't go any further because I needed virtual HMD support) and the setup and reinstall file does the same thing.

I am running on a Windows 10 computer with NIVIDIA GeForce GTX 1060, if this is important in any way.
(edit) I forgot to mention that I am using Trinus PSVR with PSMoveService.

**Comment by Cretkensigh** [comment]
Same boat as me dude, ive only manage to get 8.1.0 workinh with steamvr but i too need the virtual hmd and 8.4.0 is the one that starts support for that but cant get it to talk to steam at all. Ive suspected its something yo do with the steamvr bat file.

**Comment by Cretkensigh** [comment]
Running win10 nvidia drivers 387.92 and oculus dk1 with runtime 0.8

**Comment by Jeff07734** [comment]
I manuallly copied the files over to SteamVR. I noticed there was a line saying: ""%STEAMVR_RUNTIME_DIR%\bin\win64\vrpathreg" adddriver "%INSTALL_DIR%". I'm not sure how I'm supposed to do that manually. When I started up SteamVR, the PSMove Service worked with one problem. Only my left hand controller was being tracked. I brought my right hand controller in front of my headset and pressed start and select, but it only moved the cameras' location. I don't know if it has to do with that one line that I didn't know how to do manually. Headtracking also didn't work but I don't know if that is for this thread.

**Comment by Jeff07734** [comment]
I just looked in the PSMoveService and found this in the command prompt right after controller 1 stream started: "[2017-10-28 12:34:30.162]: ServerRequestHandler - Stop controller(1) stream" Why is it doing this and how do I stop it?

**Comment by Cretkensigh** [comment]
What files and where in steamvr, what folder?

**Comment by Cretkensigh** [comment]
And sorry man i have no idea how to fix anything on this. All i know is set up videos and forums set up guide are not working for me no matter how closely i follow them

**Comment by Jeff07734** [comment]
copy driver_psmove.dll "%INSTALL_DIR%\bin\win64\driver_psmove.dll"
-Copy the drive_psmove.dll into C:\Program Files (x86)\Steam\steamapps\common\SteamVR\drivers\psmove\bin\win64 (That is where my steam folder is.) (also if the bin\win64 folders don't exist, create them.)

copy PSMoveClient_CAPI.dll "%INSTALL_DIR%\bin\win64"
-Copy the PSMoveClient_CAPI.dll to C:\Program Files (x86)\Steam\steamapps\common\SteamVR\drivers\psmove\bin\win64

copy monitor_psmove.exe "%INSTALL_DIR%\bin\win64"
-Copy monitor_psmove.exe to C:\Program Files (x86)\Steam\steamapps\common\SteamVR\drivers\psmove\bin\win64

copy openvr_api.dll "%INSTALL_DIR%\bin\win64"
-Copy openvr_api.dll to C:\Program Files (x86)\Steam\steamapps\common\SteamVR\drivers\psmove\bin\win64

xcopy /s /i /y "resources" "%STEAMVR_RUNTIME_DIR%\drivers\psmove\resources"
-Copy the folder "resources" to C:\Program Files (x86)\Steam\steamapps\common\SteamVR\drivers\psmove\

xcopy /s /i /y configuration "%STEAMVR_RUNTIME_DIR%\drivers\psmove\configuration"
Copy the folder "configuration" to C:\Program Files (x86)\Steam\steamapps\common\SteamVR\drivers\psmove

copy driver.vrdrivermanifest "%INSTALL_DIR%"
-Copy driver.vrdrivermanifest to C:\Program Files (x86)\Steam\steamapps\common\SteamVR\drivers\psmove\ (which upon me pointing this out I think I forgot to copy this one)

All of the files should be in the main folder of your PSMoveService folder

**Comment by Cretkensigh** [comment]
Done all that, all the files ive copied were already there but still nothing comes up in steamvr. To be fair i seem to get alot of 400 errors and the hmd not being ready. What version of psmove are you using? Or steamvr bridge??

**Comment by Jeff07734** [comment]
I am using the steamvrbridge (which is what you should be using, too). The latest version of it, 1.42, and I'm using The PSMove FreePIE (But you have built-in tracking)

**Comment by Cretkensigh** [comment]
Honestly ive tried every which way you csn imagine. I have every down of the ps move service i can find and same goes for steamvr bridge. The only one that has worked following all steps was 8.1.0 of the psmove service. Even the steamvr bridge v1.0 which has been stated to be identical to it doesnt work but ill try that one again.

**Comment by Cretkensigh** [comment]
Still nothing. Do i need the "activatemultiplydriver" line?

**Comment by Jeff07734** [comment]
Yes "activateMultipleDrivers" : true," It needs to be under the steamvr section in the steamvr.vrsettings file. Also, I don't know if this is nessecary, but in C:\Program Files (x86)\Steam\steamapps\common\SteamVR\resources\settings, the Default.vrsettings file has a activateMultipleDrivers line. Try activating that too.

**Comment by Jeff07734** [comment]
Drivers are now working, controllers, HMD, cameras, every hardware is working. They're connected to SteamVR and the SteamVR Home uses and shows them, but the actual games don't. Nor do the games take button input. is there a setting in SteamVR for controllers? I'm gonna post a new thread because I'm straying away from the problem of this one.

**Comment by Cretkensigh** [comment]
Sorry man but nothings working, ive uninstalled steamvr deleted folders countless times. Nothing but version 0.9 alpha 8.1.0 works.

**Comment by Cretkensigh** [comment]
But thanks anyway best of luck

**Comment by Jeff07734** [comment]
Thank you! I hope you can get it working too!

**Comment by Cretkensigh** [comment]
Jumping jesus christ!!! I did it, i tried to run the latest oculus drivers. Failed off l course but i had to.uninstall the 0.8 oculus runtime and when i restarted my computer pow!!! They are connect now i just have to same issue you had before woth only one controller shower up,........bit hey ill take it after all that XD thanks for all your help Jeff07734 got me through some dark times XD

**Comment by Jeff07734** [comment]
Congrats! I'm glad you could get it working Cretkensigh! Sorry it took me a while to respond. I did get both controllers working, though. You have to go into steamVR settings (not in the be headset), go to applications (I think that's what the tab was called), and enable the monitor_psmove.

**Comment by Cretkensigh** [comment]
Thanks man ^.^ now i got a new issue i think one of my controllers has a bung magnetometer it will trackinh roller forward and back but has issues rolling side to side its just the one controller the others fine, it will try to line itself up bit really slowly and would favour just rolling around a magnetic field. What you recon? Chance she wreckt or software issue?

**Comment by Jeff07734** [comment]
The only thing that I can think of is to redo magnetometer calibration. Do you know of any damage done to the controller? Is it pre-used? It might just be broken. If you haven't already, try disconnecting and reconnecting the controller.

**Comment by Cretkensigh** [comment]
Its secondhand cant speak of its abusive past lol ive reset it with that button on the back and try again tomorrow. Local pawn shops got 2 and 3 cameras might have to upgrade my rig XD

**Comment by HipsterSloth** [comment]
I think it sounds like you guys got everything sorted out here. FWIW the SteamVR_InitalSetupWin64.bat is now moot with the new installer in the latest release:
https://github.com/HipsterSloth/PSMoveSteamVRBridge/releases/tag/v1.6.0
