### ISSUE TITLE
Issue with installing the .bat files.

### ISSUE THREAD

**Issue by Ub3rZ4cH** [HipsterSloth/PSMoveSteamVRBridge#3]
When I run initial setup.bat it says this...

> "Found SteamVR Runtime Dir: C:\Program Files (x86)\Steam\steamapps\common\SteamVR"
> 'SteamVR_ReinstallDriverWin64.bat' is not recognized as an internal or external command,
> operable program or batch file.
> Press any key to continue . . .

Used this before it split off to its own github and it worked just fine?

**Comment by Ub3rZ4cH** [comment]
Just copied driver_psmove.dll monitor_psmove.exe and PSMove_Client_CAPL.dll manually
but then figured I would try the "uninstall driver.bat" did that and it worked, so I used re-install and it worked, then I run initial setup again and got this...

 

> "Found SteamVR Runtime Dir: C:\Program Files (x86)\Steam\steamapps\common\SteamV
> R"
> Could Not Find C:\Users\Zach\Downloads\Compressed\PSMoveSteamVRBridge_1.0.0\Stea
> mVR_SetDriverVarsWin64.bat
> "(Re)Installing PSMoveService SteamVR Win64 driver..."
>         1 file(s) copied.
>         1 file(s) copied.
>         1 file(s) copied.
> The system cannot find the file specified.
> resources\icons\base_status_error.png
> resources\icons\base_status_off.png
> resources\icons\base_status_ready.png
> resources\icons\base_status_ready_alert.png
> resources\icons\base_status_standby.png
> resources\icons\controller_status_error.png
> resources\icons\controller_status_off.png
> resources\icons\controller_status_ready.png
> resources\icons\controller_status_ready_alert.png
> resources\icons\controller_status_ready_low.png
> resources\overlays\need_alignment_gesture.png
> resources\rendermodels\dualshock4_controller\dualshock4_controller.json
> resources\rendermodels\dualshock4_controller\dualshock4_controller.mtl
> resources\rendermodels\dualshock4_controller\dualshock4_controller.obj
> resources\rendermodels\dualshock4_controller\dualshock4_controller.png
> resources\rendermodels\dualshock4_controller\dualshock4_lightbar.mtl
> resources\rendermodels\dualshock4_controller\dualshock4_lightbar.obj
> resources\rendermodels\dualshock4_controller\dualshock4_thumbnail.png
> resources\rendermodels\navi_controller\frame.png
> resources\rendermodels\navi_controller\navi_controller.mtl
> resources\rendermodels\ps3eye_tracker\body.png
> resources\rendermodels\ps3eye_tracker\ps3eye_thumbnail.png
> resources\rendermodels\ps3eye_tracker\ps3eye_tracker.json
> resources\rendermodels\ps3eye_tracker\ps3eye_tracker.mtl
> resources\rendermodels\ps3eye_tracker\ps3eye_tracker.obj
> resources\rendermodels\psmove_controller\frame.png
> resources\rendermodels\psmove_controller\psmove_controller.json
> resources\rendermodels\psmove_controller\psmove_controller.mtl
> resources\rendermodels\psmove_controller\psmove_controller.obj
> resources\rendermodels\psmove_controller\psmove_thumbnail.png
> 30 File(s) copied
> configuration\driver.vricons
> 1 File(s) copied
>         1 file(s) copied.
> "Done"
> Press any key to continue . . .
>

**Comment by Ub3rZ4cH** [comment]
Monitor psmove stopped working, I think when I run that manually it states that openVR api.dll is missing? 0.o

**Comment by HipsterSloth** [comment]
I believe this was fixed in the v1.1.0 release and I just forgot to resolve this issue.
