### ISSUE TITLE
ps button mapping

### ISSUE THREAD

**Issue by soloma84** [HipsterSloth/PSMoveSteamVRBridge#38]
Hello! Help me please! I remap ps button to d pad down. But always when i pressed on ps button after d pad down. Appears Steam vr menu. How i can fix this? Thanks﻿

**Comment by HipsterSloth** [comment]
This issue is moot now with the new release:
https://github.com/HipsterSloth/PSMoveSteamVRBridge/releases/tag/v1.6.0
