### ISSUE TITLE
Compiling from source using VS2017

### ISSUE THREAD

**Issue by SuperEvenSteven** [HipsterSloth/PSMoveSteamVRBridge#44]
Just thought I'd put this here for anyone else looking to compile the driver with VS2017.

I installed:
CMake 3.10 and opted to add it to the PATH during install
VS2017 with the C/C++ development pack and under the Individual tab I chose "MFC and ATL support (x86 and x64)" down the bottom.

Followed the instructions on the wiki page but I had to make 2 changes to the files that generate the solution project.

Change this from 14 to 17:
https://github.com/HipsterSloth/PSMoveSteamVRBridge/blob/bed9d49ed080343b97719bd7babf75234bac7c6e/CMakeLists.txt#L8

Change this from: "Visual Studio 14 2015 Win64" to: Visual Studio 15 2017 Win64
https://github.com/HipsterSloth/PSMoveSteamVRBridge/blob/bed9d49ed080343b97719bd7babf75234bac7c6e/scripts/msvc/InitialSetupOfficialPSM_X64.bat#L27

In order to work on this project error free from checkout you need to have the source of the PSMoveService available in this driver's include path. Instructions on how to do that are further ahead.

Now run the InitialSetupOfficialPSM_X64 from a Developer Command Prompt.

The vs2017 solution project files should be generated. Open up the solution in VS2017 and when it finishes loading add the PSMoveService/src folder to the includes. Right-click driver_psmoveservice project->properties->C++->Add include dir dropdown. Now all the PSMoveService classes are properly referenced in this project.

To build just do a clean, build from the menu. You should see 6 projects build skipping the Install.

**Comment by HipsterSloth** [comment]
@SuperEvenSteven  Thanks for these steps! Now that the 1.6.0 release is out I'm going to be upgrading PSMoveService and PSMoverSteamVRBridge over to 2017.

**Comment by SuperEvenSteven** [comment]
@HipsterSloth no probs. Given the recent changes of at 1.6.0 these instructions will be out of date. You should just need to modify this file:

`https://github.com/HipsterSloth/PSMoveSteamVRBridge/blob/master/build.properties`

to use:

`cmake.build.generator.windows=Visual Studio 15 2017 Win64`

Then run a clean.bat and generate.bat to generate the VS 2017 project files and open them up.

I'll close this off and work on adding some instructions on the wiki.
