### ISSUE TITLE
No pointing ray in steamVR menu (and other places).

### ISSUE THREAD

**Issue by AdrianJamrozik** [HipsterSloth/PSMoveSteamVRBridge#45]
Hi!

I got following problem - when in game and pressing PS button to open steamVR the pointing ray disappear and I can't select anything. The pointing works when in steamVR home and in google earth VR. Also sound shield has a problem - game works ok but when I open virtual keyboard (e.g. for searching youtube) the pointing ray also disappears.

Is there any workaround for this? What can I attach to help with investigation?

I am using 1.4.2 version.

I noticed that this issue has been posted in forum, please indicate if there is any chance of fixing this...

Thank you!
Also - great project, I am under great impression of your work!

**Comment by EchoTech0** [comment]
I would also like to say I have this issue too and would like to know if there is a know solution. I have installed all the drivers and files twice, re-done the setup (got 2 more cameras to total 4) and still have the no-laser in the steam overlay.

**Comment by admiralspeedy** [comment]
I'm pretty sure this was caused by an update to OpenVR.

**Comment by machmar** [comment]
I have also this problem (for like five months)

**Comment by oldmanbluntz** [comment]
The problem still exists.

**Comment by HipsterSloth** [comment]
The new 1.6.0 release that I just put out supports the new SteamVR input API:
https://github.com/HipsterSloth/PSMoveSteamVRBridge/releases/tag/v1.6.0
