### ISSUE TITLE
steamvr no buttons

### ISSUE THREAD

**Issue by peterjordan1977** [HipsterSloth/PSMoveSteamVRBridge#47]
i have no buttons only the ps button is this a issue with steam can you post a guide on how to downgrade steamVR for people having issues ?

**Comment by jimnarey** [comment]
I also have this issue. It could only be solved by opting into the openvr-inputemulator-temporary beta in Steam VR. However, this is there to support deprecated functionality and when it is used, Driver4VR and Fallout 4 VR won't work.

This is a great piece of software but as things stand it can't really be used.

**Comment by oldmanbluntz** [comment]
The devs just need to add support for the new openvr api's, so that PsMoveService will work with the new api's.

**Comment by HipsterSloth** [comment]
The new 1.6.0 release that I just put out supports the new SteamVR input API:
https://github.com/HipsterSloth/PSMoveSteamVRBridge/releases/tag/v1.6.0
