### ISSUE TITLE
Can we do bindings per game "profiles"

### ISSUE THREAD

**Issue by vrokolos** [HipsterSloth/PSMoveSteamVRBridge#49]
Different mappings per game? Is there anything like this?

**Comment by HipsterSloth** [comment]
This is what the new SteamVR Input system supports:
https://steamcommunity.com/games/250820/announcements/detail/3809361199426010680

The new 1.6.0 release that I just put out supports the new SteamVR input API:
https://github.com/HipsterSloth/PSMoveSteamVRBridge/releases/tag/v1.6.0

With this you can do per game settings. I'm working on updating the wiki now to describe how the new setup works.

**Comment by vrokolos** [comment]
Can we have a list of games that people have successfully mapped to double PS Moves with this?

**Comment by HipsterSloth** [comment]
I literally just put out 1.6.0 about 1hr ago so there is no such official list yet. I've tested locally in SteamVR Home and Space Pirate Trainer. I would give it a bit of time and then hopefully more people will have game bindings available that they can share.
