### ISSUE TITLE
PS Move controller button not working

### ISSUE THREAD

**Issue by Altr4** [HipsterSloth/PSMoveSteamVRBridge#52]
I already set up my PS Move to the point where I can see it as a Vive controller and move it around. However, None of the button do anything. The only button that work is the ps button which open the menu. There is also no pointer appear from the controller

**Comment by JRaegames** [comment]
I suggest using SteamVR Beta and keep the controller disconnected until after SteamVR opens then connect it. Works for me.

James Rogowy
Senior Web Developer
www.digicandesigns.com

**Comment by Altr4** [comment]
So I change SteamVR to Beta and open PSmove after I open SteamVR. The button and the pointer still didn't work. But your suggestion gives a hint though, I set change the SteamVR to use the "openvr..." option and it worked! Thank you so much for your help!

**Comment by JRaegames** [comment]
So are we getting a new release then? My fingers are crossed!!!!

James Rogowy
Senior Web Developer
www.digicandesigns.com

**Comment by oivio** [comment]
hey Altr4, how did you manage to use "openvr..." Since I am doing it and SteamVr do always crash.
