### ISSUE TITLE
Steam does not see the new psmove

### ISSUE THREAD

**Issue by Rain343** [HipsterSloth/PSMoveSteamVRBridge#53]
I assembled a new PSMoveServiсe ZCM2U and he sees controllers, but Steam does not see it. Maybe need to update monitor_psmove or driver_psmove, if it is not difficult? Or I do not know what I'm doing wrong.

**Comment by JRaegames** [comment]
I recommend installing the Steam VR OSVR Beta version… It seems to work with PSMoveService nicely. If that doesn’t work then try leaving your controllers disconnected until you are in SteamVR and then connect.

James.
