### ISSUE TITLE
PS move button problem and tracking in Steam VR

### ISSUE THREAD

**Issue by Gonyczz** [HipsterSloth/PSMoveSteamVRBridge#54]
Hello.,
I'm already desperate. I'm trying to run PS move on Steam Vr for 3 days :( I have the drivers set up, paired and calibrated, but I still have problems with SteamVR.

- Freepie does not work as it should. It follows pinpong ball but also one PS move. How can I solve this problem?
- Driver orientation is still out of body. I think it's a pinpong ball and PS move problem that track head tracking.
- I'm still updating and overwriting steamvr.vrsettings and I can not add buttons here. Now the buttons do not work.

I use:
Vridge (latest version)
Steam VR (Latest Version)
PS move PS3 with mini usb
Last - PSMoveSteamVRBridge
Last- Freepie
Last - PSMoveFreepieBridge-Release15
- I've calibrated everything (by videos on youtube)

My steamvr.vrsettings:
{
   "GpuSpeed": {
      "gpuSpeed0": 336,
      "gpuSpeedCount": 1,
      "gpuSpeedDriver": "24.21.13.9907",
      "gpuSpeedHorsepower": 336,
      "gpuSpeedRenderTargetScale": 1.5199999809265137,
      "gpuSpeedVendor": "NVIDIA GeForce GTX 1060 6GB"
      "gpuSpeedVersion": 2
   },
   "driver_vridge": {
      "fakeSensorEnabled": true,
      "fovValues": "37.78 41.33 44.89 44.89",
      "hmdMode": 0,
      "renderScale": 100,
      "useDefaultFov": true,
      "windowHeight": 1440,
      "windowWidth": 2560
   },
   "steamvr": {
      "installID": "14353893826071132617",
      "mirrorViewGeometry": "0 0 1280 720",
      "supersampleScale": 1.5199999809265137
   }
}

Thank you very much

**Comment by Gonyczz** [comment]
Is it still functional? The buttons do not work and I do not know what to do?

**Comment by TPiotr** [comment]
I had same issue (no pointer & no working buttons except ps home) I solved it by switching normal steam vr version to beta (choose something like vr input emulator branch (I don't remember exact branch name sorry)) after that everything was working as it should.

**Comment by oivio** [comment]
> I had same issue (no pointer & no working buttons except ps home) I solved it by switching normal steam vr version to beta (choose something like vr input emulator branch (I don't remember exact branch name sorry)) after that everything was working as it should.

do you mean hand **branch**  from https://github.com/HipsterSloth/PSMoveSteamVRBridge/branches? I did try Beta itself but it didn't work.

**Comment by TPiotr** [comment]
https://imgur.com/a/miUkXl5 here follow this and try

**Comment by oivio** [comment]
> https://imgur.com/a/miUkXl5 here follow this and try

Dzięki Piotrku :) to już wiem ale nie wiem skąd ściągnąć przez Ciebie wspomniany PSMoveSteamVRBridge a raczej który branch? Bo ogólnie sama zmiana na OpenVR robi mi kompletnego crasha.  A zmiana na wersje SteamVr Beta działa tak samo jak ogólna.

**Comment by TPiotr** [comment]
Kurde co do brancha chodziło mi własnie o to (po prostu ta wersja beta ma w nazwie słowo "branch" i to spowodowało niezrozumienie) :/, też mam tak że na zwykłej becie nie widać żadnej zmiany dopiero na tym "openvr-emulator" zaczyna działać poprawnie, kiedyś chyba działało mi z "v1527... 6/21/2018 hotfix" więc możesz spróbować ale pewnie już testowałeś każdą możliwą opcję więc niestety moje pomysły tutaj się kończą :(.

**Comment by oivio** [comment]
No niestety próbowałem każdej wersji ale bez skutku. Dodatkowo nawet testowałem wersji OpenVr z Githuba ale ten sam problem wystąpił. SteamVR robił crash. Może inaczej, moze to mi pomoże. Czy jesteś w stanie napisać jakie wersje używasz? Mam tutaj na myśli PSMoveSteamVRBridge? Np czy to wersja 1.4.2? I czy do tego masz jeszcze coś zainstalowane oczywiście poza tą opcją OpenVr?

Ps: Co by nie było to dzięki za odpowiedź.

**Comment by TPiotr** [comment]
Używam 1.4.2 i tylko psmovesteamvrbridge i wszystko działa więc niestety nie mam pojęcia co u ciebie może być nie tak :/, jeśli używasz psmovesteamvrbridge tylko do kontrolerów ps move (bez kamerek do ustalania pozycji) może driver4vr by pomógł bo jak kojarzę on nie łączy się z psmovesteamvrbridge tylko z normalnym ps move service i samemu "wstrzykuje" dane o kontrolerach do steam vr (choć mogę się mylić bo nie korzystałem jeszcze z tego oprogramowania).

**Comment by oivio** [comment]
Dzięx, Muszę przyznać że posiadam pełną wersje Drive4vr ale mam wrażenie ze optymalizacja jego jest dość słaba i z po dłuższym czasie mi PSMove w nim świruje. Dlatego też próbuję połączyć Kinect2Vr  z PsmovrBridge.

**Comment by HipsterSloth** [comment]
New 1.6.0 release is out that fixes the button issue:
https://github.com/HipsterSloth/PSMoveSteamVRBridge/releases/tag/v1.6.0

I'm working on updating the wiki now since the controller button config setup is now different (no longer set stuff in steamvr.vrsettings)
