### ISSUE TITLE
Controllers do not work in Overlay or SteamVR Home

### ISSUE THREAD

**Issue by Thestickman391** [HipsterSloth/PSMoveSteamVRBridge#58]
They work if I opt-in to "openvr-inputemulator-temporary" in SteamVR beta's but the problem there is that Revive doesn't work in that beta and the option to rebind controls doesn't appear in that beta either. Is there a fix or workaround for this?

**Comment by HipsterSloth** [comment]
Not yet. I need to update the steamvr plugin to use the new input interface. @SuperEvenSteven did a bunch of work on this in his fork of PSMoveSteamVRBridge. I need to incorporate that work and make a new release.

**Comment by Thestickman391** [comment]
Alright, thanks for replying

**Comment by stickman89** [comment]
I noticed that on your v1.5.0 github page there was no compiled binary release under assets, just source files. Which would tie in with what you've just mentioned. There should be notice for this, as on the cboulay psmoveservice github release page it links to that tag release as if it is usable, and a requirement. I thought I was going crazy, couldn't figure out where my controllers had gone too.

**Comment by SuperEvenSteven** [comment]
Appologies for the delay in the PR ,I've been distracted by school and work at the moment. Looking to finish this and submit it next month.

**Comment by HipsterSloth** [comment]
@SuperEvenSteven Oh no worries at all about time! Thanks so much for you work on that so far. Let me know if I can be of any help with that PR.

**Comment by HipsterSloth** [comment]
@Thestickman391 Also I just saw your other comment in e-mail regarding the missing 1.5.0 release binaries. Sorry about that! I just uploaded those.

**Comment by stickman89** [comment]
Actually that was me. We strangely have similar nicknames. Coincidence... Thanks for the update. Will that happen to solve the lack of functional button mapping in steam? I couldn't even get the openinput-emulator branch to launch vr server with psmoveservice and driver4vr (for freetrack hmd tracking) running/installed.

**Comment by stickman89** [comment]
The answer to my own question is no. Ha. Apparently I need to look up more. The answer is what's falling towards me.

**Comment by Thestickman391** [comment]
Hah, our nicknames are quite similar, what are the chances?

**Comment by oldmanbluntz** [comment]
Sorry to bug about this, as it's been a few weeks. I was just curious if there were any updates on this. I decided to get the setup running again this weekend, and this issue is still there. I assume you just have been busy and haven't pushed the update yet, which is perfectly fine of course. Thank you for your time and work on this.

**Comment by HipsterSloth** [comment]
There is a new 1.5.1 update here:
https://github.com/HipsterSloth/PSMoveSteamVRBridge/releases/tag/v1.5.1

Though that release just contains support for the ZCM2 psmove controller and a hot fix for a controller jitter issue. It'll probably be a while before I can get to the SteamVR overlay issue. What little free time I have is currently being spent on getting https://github.com/HipsterSloth/PSVRTracker working.

**Comment by oldmanbluntz** [comment]
Got ya. I was hoping the work superevensteven was mentioning he would be submitting next month last month would be coming sooner than awhile. I already downloaded the 1.5.1 hoping it was the fix, but as you said, it was jitter issues and support for the ps4 move controllers. It's kinda poopy that I'm unable to use any of this right now, as I use VRidge, and it doesn't work with the beta open vr steamvr files on steam. It's annoying not being able to actually play anything, so I was hoping for it to be resolved. But, I'll just patiently wait for the fix To come in.

**Comment by HipsterSloth** [comment]
@SuperEvenSteven I wanted to give a heads-up to prevent work collision. 

I pulled over your work on this so far into this branch:

https://github.com/HipsterSloth/PSMoveSteamVRBridge/commits/openvr_update

I'll be working over the next week or so to get the rest of the refactor into shape. I might have a question or two for you regarding appveyor in a few days, but so far everything else makes sense. I got your new code building and am filling out the new VirtualController implementation now. 

Thanks for all of your work on this! I'm digging the new class structure and cmake generation framework..

**Comment by SuperEvenSteven** [comment]
Thanks @HipsterSloth I'm finishing final uni exams this week but will be able to turn my focus back on this project later this week.

**Comment by MyNameKuba** [comment]
So new update should be ready even this month? I'll be very happy :)

**Comment by HipsterSloth** [comment]
New 1.6.0 release is out that fixes this issue:
https://github.com/HipsterSloth/PSMoveSteamVRBridge/releases/tag/v1.6.0

I'm working on updating the wiki now since the controller button config setup is now different (no longer set stuff in steamvr.vrsettings)
