### ISSUE TITLE
Move controllers with wrong orientation

### ISSUE THREAD

**Issue by LowderPlay** [HipsterSloth/PSMoveSteamVRBridge#61]
Hello! I use my controllers with VR. Their orientation is very bad, with both controllers. While playing, they are not stable, so it very hard to play. [Video](https://www.youtube.com/watch?v=9v8RnLwlqow) describes their behaviour. I don't think that this is a bug.

**Comment by oivio** [comment]
what version of PSMoveSteamVRBridge do you use?
