### ISSUE TITLE
No laser pointer for VR Dashboard

### ISSUE THREAD

**Issue by 8osM3Rka** [HipsterSloth/PSMoveSteamVRBridge#63]
I can open VR Dashboard but there is no laser pointer for either of PSMoves
What can i do about this except than opting into openvr-inputemulator-temporary beta?

**Comment by Thestickman391** [comment]
Duplicate of #58

**Comment by 8osM3Rka** [comment]
Oh, it seems to work with steamvr beta

**Comment by 8osM3Rka** [comment]
Yeah, it works fine with SteamVR Beta, please add this fix to the Wiki 'till the next release
