### ISSUE TITLE
headTracking - can add a third psmove on the headset to Have HeadTracking ?

### ISSUE THREAD

**Issue by ychoucha** [HipsterSloth/PSMoveSteamVRBridge#7]
Hello there, 
can add a third psmove on the headset to Have HeadTracking ?

thanks for this exelent works

**Comment by zelmon64** [comment]
Hello @ychoucha,

This sort of question should be asked on the [google group](https://groups.google.com/forum/#!forum/psmoveservice). 

The answer depends on what headset you have. If you're using VRidge it can be done using [PSMoveFreepieBridge](https://bitbucket.org/hawkinse/psmovefreepiebridge/downloads/). If you're not then it's probably not currently possible but that's what issue #1 is about.

**Comment by ychoucha** [comment]
Hello, 

thanks for u respond,  i m using Pimaxx 4k-UHD, the psmove controler works perfectly with 2 psEye, now i m just looking to make the last things missing on this headset the headTracking

thanks
