### ISSUE TITLE
No controller's in steam vr

### ISSUE THREAD

**Issue by Iggynik** [HipsterSloth/PSMoveSteamVRBridge#83]
Hi. Have configured psmoveservice with camera and ps move controller. Before starting riftcat I started ps move service and steam vr do not see my controller and ps move not gloving.
Tryed to use ps move steam vr service bridge 1.6.0. and ps move service release 8.1
Need any help you could provide.
P.S. before version 1.6.0 used 1.4.2 and it worked. But there's were problems with button mapping, also when I try to open through steam vr home button mapping there is black screen.
Now after using(that was not working) version 1.6.0 version 1.4.2 also not working.
P.P.S. English language is not my native language. So sorry for some misunderstanding.

**Comment by Expora9** [comment]
Have you installed the Steam Bridge too?

**Comment by Iggynik** [comment]
Yes. Also I launched This files in that order
![Безымянный](https://user-images.githubusercontent.com/49561945/56048410-21f54600-5d50-11e9-9d88-1919a06b720f.png)

**Comment by Iggynik** [comment]
I think th better solution for me is to reinstall Windows with formating my system drive(creting a ghost image for further expirements).
Becouse I tryed to unninstal all PS move and steam vr bridge and Steam vr files and reinstall them, and this did not helped me.
P.S. After my expirements with different versions. When I click turn off trnslation in RiftCat. Steam VR getting stucked. It just says Exiting but nothing happens untill I dellete SteamVR procces from task manager.

**Comment by Expora9** [comment]
OK see you when ur done
